config/routes.rb
SklepRails3::Application.routes.draw do
  resources :koszyks

  resources :produkts

  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/nie_zakladalem_konta' => 'users_#pomylka'
  match '/zgloszenie' => 'users_#zgloszenie'
  match '/dodaj_do_koszyka' => 'koszyks_#create'
  match '/wyczysc_koszyk' => 'koszyks_#wyczysc_koszyk'
  match 'kontakt' => 'produkts#kontakt'
  match 'panel' => 'users#panel_administratora'
  match '/nie_pamietam_hasla' => 'user_sessions_#nie_pamietam_hasla'
  match '/przypomnienie_hasla' => 'user_sessions#przypomnienie'
  match '/reset_hasla' => 'user_sessions_#reset_hasla'
  match '/nowe_haslo' => 'users#nowe_haslo'
  root :to => 'produkts#index'

end

app/models/produkt.rb
class Produkt < ActiveRecord::Base
  attr_accessible :cena, :obrazek_url, :opis, :tytul
  validates :tytul, length: { in: 3..25 }, allow_blank: false
  validates :cena, :format => { :with => /^\d+??(?:\.\d{0,2})?$/, :message => 'ma niepoprawny format. Maksymalnie 2 miejsca po przecinku!' }, allow_blank: false
  validates :obrazek_url, :format =>{ :with => URI::regexp(%w(http https)), :message => 'ma niepoprawny adres URL.' }, allow_blank: false
end

app/controllers/produkts_controller.rb
class ProduktsController < ApplicationController
  # GET /produkts
  # GET /produkts.json
  def index
    @produkts = Produkt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produkts }
    end
  end

  # GET /produkts/1
  # GET /produkts/1.json
  def show
    @produkt = Produkt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produkt }
    end
  end

  # GET /produkts/new
  # GET /produkts/new.json
  def new
    if current_user
	if ((current_user.username == 'Administrator') || (current_user.username =='Moderator'))
		@produkt = Produkt.new

		respond_to do |format|
      			format.html # new.html.erb
      			format.json { render json: @produkt }
    		end
	else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do dodania produktu!"
	end
    else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do dodania produktu!"
    end
  end

  # GET /produkts/1/edit
  def edit
    if current_user 
	if ((current_user.username == 'Administrator') || (current_user.username =='Moderator'))
    	@produkt = Produkt.find(params[:id])
	else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do tej operacji!"
	end
    else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do tej operacji!"
    end
  end

  # POST /produkts
  # POST /produkts.json
  def create
    if current_user
	if ((current_user.username == 'Administrator') || (current_user.username =='Moderator'))
    		@produkt = Produkt.new(params[:produkt])
		@produkt.rozmiarxs = params[:rozmiarxs]
		@produkt.rozmiars = params[:rozmiars]
		@produkt.rozmiarm = params[:rozmiarm]
		@produkt.rozmiarl = params[:rozmiarl]
		@produkt.rozmiarxl = params[:rozmiarxl]
		@produkt.rozmiarxxl = params[:rozmiarxxl]

   		 respond_to do |format|
      			if @produkt.save
        		format.html { redirect_to @produkt, notice: 'Produkt dodany do bazy.' }
        		format.json { render json: @produkt, status: :created, location: @produkt }
      			else
        		format.html { render action: "new" }
        		format.json { render json: @produkt.errors, status: :unprocessable_entity }
      			end
    		end
	else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do dodania produktu!"
	end
    else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do dodania produktu!"
    end
  end

  # PUT /produkts/1
  # PUT /produkts/1.json
  def update
    if current_user
	if ((current_user.username == 'Administrator') || (current_user.username =='Moderator'))
    		@produkt = Produkt.find(params[:id])
		@produkt.rozmiarxs = params[:rozmiarxs]
		@produkt.rozmiars = params[:rozmiars]
		@produkt.rozmiarm = params[:rozmiarm]
		@produkt.rozmiarl = params[:rozmiarl]
		@produkt.rozmiarxl = params[:rozmiarxl]
		@produkt.rozmiarxxl = params[:rozmiarxxl]

    		respond_to do |format|
      			if @produkt.update_attributes(params[:produkt])
        		format.html { redirect_to @produkt, notice: 'Produkt uaktualniono.' }
        		format.json { head :no_content }
      			else
        		format.html { render action: "edit" }
        		format.json { render json: @produkt.errors, status: :unprocessable_entity }
      			end
    		end
	else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do edycji produktu!"
	end
    else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do edycji produktu!"
    end
  end

  # DELETE /produkts/1
  # DELETE /produkts/1.json
  def destroy
    if current_user
	if current_user.username == 'Administrator'||'Moderator'

    	@produkt = Produkt.find(params[:id])
    	@produkt.destroy

    	respond_to do |format|
      		format.html { redirect_to produkts_url }
      		format.json { head :no_content }
    	end
	end
    else
	redirect_to (:produkts), :notice => "Nie masz uprawnien do usuniecia produktu!"
    end
  end
end

app/helpers/produkts_helper.rb
module ProduktsHelper
end

app/views/produkts/_form.html.erb
  <% if @produkt.errors.any? %>
    <div id="error_explanation">
      <% if  (@produkt.errors.count)==1  %>
      <h2 style="color: rgb(185, 74, 72);">Produkt nie został dodany z powodu jednego błędu</h2>
    <% elsif (@produkt.errors.count)>1 %>
	<h2 style="color: rgb(185, 74, 72);">Produkt nie został dodany z powodu <%= @produkt.errors.count %> błędów</h2>
    <% end %>

      <ul>
      <% @produkt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="nowy_produkt_tytul">
    <%= f.label :tytuł_produktu %>:<br />
    <%= f.text_field :tytul %>
  </div>
  <div class="nowy_produkt_cena">
    <%= f.label :cena %>:<br />
    <%= f.text_field :cena %>
  </div>
<br />
<br />
  <div class="nowy_produkt_rozmiary">
    Dostępne rozmiary:<%= check_box_tag 'rozmiarxs', '1' %> XS <%= check_box_tag 'rozmiars', '1' %> S <%= check_box_tag 'rozmiarm', '1' %> M <%= check_box_tag 'rozmiarl', '1' %> L <%= check_box_tag 'rozmiarxl', '1' %> XL <%= check_box_tag 'rozmiarxxl', '1' %> XXL
 </div>
<br />
  <div class="nowy_produkt_opis">
    <%= f.label :opis %>:<br />
    <%= f.text_area :opis %>
  </div>
<br />
  <div class="nowy_produkt_obrazek">
    <%= f.label :obrazek_url_produktu %>:<br />
    <%= f.text_field :obrazek_url %>
  </div>
<br />

app/views/produkts/edit.html.erb
<h1 style="border-bottom: 2px solid rgb(229, 229, 229);">Edycja Produktu</h1>
<%= simple_form_for @produkt, :html => { :multipart => true } do |f| %>
<%= render partial: 'form', locals: { f: f } %>

 <%= f.button :submit, :value => 'Aktualizuj Produkt' %><%= button_tag "Powrót",:type => 'button',:class => 'button',:onclick => "location.href = '#{produkts_url}'" %>
<% end %>

app/views/produkts/index.html.erb
<% title "Produkty Wszystkie" %>
<br />
<div class="produkty">
<% @produkts.each do |produkt| %>
<div class="produkt">
<%= link_to produkt.tytul, produkt %><br />
<%= image_tag(produkt.obrazek_url, :class => "produkty_obrazek", :size => "220x269") %><br />
<div class="cena"><b>Cena</b>: <%= number_with_precision(produkt.cena, :precision => 2) %> zł</div><br />
<% if current_user %>
<% if ((current_user.username == 'Administrator')||(current_user.username == 'Moderator'))%>
<%= link_to 'Show', produkt %> | <%= link_to 'Edit', edit_produkt_path(produkt) %> | 
<%= link_to 'Destroy', produkt, confirm: 'Are you sure?', method: :delete %>
<% end %>
<% end %>
</div>
<% end %>
</div>

app/views/produkts/kontakt.html.erb
<% title "Kontakt" %>
<h1 style="border-bottom: 2px solid rgb(229, 229, 229);"><%= yield(:title) %></h1>
<img src="http://m1l05z.pl/images/kontakt.gif" width="100%">
<br><br><br>
<center><b>Cały kod sklepu został napisany ręcznie bez żadnych gotowców</b>
<br><br>
<b>Jest to sklep z artykułami odzieżowymi.</b>
<br><br>
<b>Strona wciąż w budowie.</b>
<br><br>
Sklep napisał: <a href="http://m1l05z.pl">Miłosz Osiński</a></center>

app/views/produkts/new.html.erb
<h1 style="border-bottom: 2px solid rgb(229, 229, 229);">Dodaj Produkt</h1>
<%= simple_form_for @produkt, :html => { :multipart => true } do |f| %>
<%= render partial: 'form', locals: { f: f } %>

 <%= f.button :submit, :value => 'Dodaj Produkt' %><%= button_tag "Powrót",:type => 'button',:class => 'button',:onclick => "location.href = '#{produkts_url}'" %>
<% end %>

app/views/produkts/show.html.erb
<% title @produkt.tytul %>
<br />
<%= form_tag "/dodaj_do_koszyka" do %>
<div class="produkt_show">
<div class="produkt_show_obrazek">
<%= image_tag(@produkt.obrazek_url, :class => "produkty_obrazek", :size => "260x319") %>
</div>
<div class="produkt_show_info">
<div class="produkt_show_tytul">
<%= @produkt.tytul %>
</div>
<div class="produkt_show_cena">
cena: <strong><%= number_with_precision(@produkt.cena, :precision => 2)    %> zł</strong>
<br />
rozmiar:
<font style="font-size:18px;font-weight:bold;color:black;">
<% if @produkt.rozmiarxs == "1" %>
  <%= radio_button_tag :rozmiar, 'XS' %> 
  <%= label_tag :rozmiar_xs, 'XS', :value => 'XS' %>
<% end %>
<% if @produkt.rozmiars == "1" %>
  <%= radio_button_tag :rozmiar, 'S' %>
  <%= label_tag :rozmiar_s, 'S', :value => 'S' %>
<% end %>
<% if @produkt.rozmiarm == "1" %>
  <%= radio_button_tag :rozmiar, 'M' %>
  <%= label_tag :rozmiar_m, 'M', :value => 'M' %>
<% end %>
<% if @produkt.rozmiarl == "1" %>
  <%= radio_button_tag :rozmiar, 'L' %>
  <%= label_tag :rozmiar_l, 'L', :value => 'L' %>
<% end %>
<% if @produkt.rozmiarxl == "1" %>
  <%= radio_button_tag :rozmiar, 'XL' %>
  <%= label_tag :rozmiar_xl, 'XL', :value => 'XL' %>
<% end %>
<% if @produkt.rozmiarxxl == "1" %>
  <%= radio_button_tag :rozmiar, 'XXL' %>
  <%= label_tag :rozmiar_xxl, 'XXL', :value => 'XXL' %>
<% end %>
<% if ((@produkt.rozmiarxs == nil)&&(@produkt.rozmiars == nil)&&(@produkt.rozmiarm == nil)&&(@produkt.rozmiarl == nil)&&(@produkt.rozmiarxl == nil)&&(@produkt.rozmiarxxl == nil)) or  ((@produkt.rozmiarxs == "0")&&(@produkt.rozmiars == "0")&&(@produkt.rozmiarm == "0")&&(@produkt.rozmiarl == "0")&&(@produkt.rozmiarxl == "0")&&(@produkt.rozmiarxxl == "0")) %>
<%= label_tag :brak_produktu, 'Brak Produktu', :value => 'Brak Produktu' %>
<% end %>
</font>
</div>
<br />
<% if ((@produkt.rozmiarxs == nil)&&(@produkt.rozmiars == nil)&&(@produkt.rozmiarm == nil)&&(@produkt.rozmiarl == nil)&&(@produkt.rozmiarxl == nil)&&(@produkt.rozmiarxxl == nil)) or  ((@produkt.rozmiarxs == "0")&&(@produkt.rozmiars == "0")&&(@produkt.rozmiarm == "0")&&(@produkt.rozmiarl == "0")&&(@produkt.rozmiarxl == "0")&&(@produkt.rozmiarxxl == "0")) %>
<% else %>
 <%= text_field_tag :koszyk_ilosc, "1" %><strong> x </strong><%= submit_tag "Dodaj do Koszyka", :class => "button" %>
<% end %>
</div>
<br />
<div class="produkt_show_opis">
  <%= simple_format(@produkt.opis) %>
</div>
</div>
<%= text_field_tag :koszyk_produkt_id, @produkt.id %>
<%= text_field_tag :koszyk_produkt_tytul, @produkt.tytul %>
<%= text_field_tag :koszyk_cena, @produkt.cena %>
<%= text_field_tag :koszyk_rozmiar %>
<% end %>
<% if current_user && current_user.username == "Administrator" %>
<%= link_to 'Edit', edit_produkt_path(@produkt) %> |
<% end %>
<%= link_to 'Wróć do listy', produkts_path %>
</div>