config/routes.rb
SklepRails3::Application.routes.draw do
  resources :koszyks

  resources :produkts

  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/nie_zakladalem_konta' => 'users_#pomylka'
  match '/zgloszenie' => 'users_#zgloszenie'
  match '/dodaj_do_koszyka' => 'koszyks_#create'
  match '/wyczysc_koszyk' => 'koszyks_#wyczysc_koszyk'
  match 'kontakt' => 'produkts#kontakt'
  match 'panel' => 'users#panel_administratora'
  match '/nie_pamietam_hasla' => 'user_sessions_#nie_pamietam_hasla'
  match '/przypomnienie_hasla' => 'user_sessions#przypomnienie'
  match '/reset_hasla' => 'user_sessions_#reset_hasla'
  match '/nowe_haslo' => 'users#nowe_haslo'
  root :to => 'produkts#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
    
    respond_to do |format|
      if @user_session.save 
        format.html { redirect_to(:produkts, :notice => 'Zalogowany!') }
        format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(:produkts, :notice => 'Wylogowany!') }
      format.xml { head :ok }
    end
  end

end

app/views/user_sessions/_form.html.erb
<style>
.form-inputs label{
	font-size:18px;
}
   
</style>
<%= simple_form_for(@user_session) do |f| %>
<% if f.error_notification %>
<h4 style="color: rgb(185, 74, 72);">Logowanie nie powiodło się, popraw błędy i spróbuj ponownie.</h4>
<% end %>

    
  <div class="form-inputs">
    <%= f.input :username, :label => 'Nazwa Użytkownika', :placeholder => 'np. kowalski' %>
    <br />
    <%= f.input :password, :label => 'Hasło', :placeholder => '*******' %>
  </div>
<br>
<%= f.check_box :remember_me %><%= f.label :zapamietaj_mnie %>
<br /><br /><br />
    <%= f.button :submit, :value => 'Zaloguj się'%> <%= button_tag "Powrót",:type => 'button',:class => 'button',:onclick => "location.href = '#{produkts_url}'" %>
<% end %>

app/views/user_sessions/_logowanie.erb
<%= form_for(@user_session || UserSession.new) do |f| %>

  <div class="logowanie_domowa">
    <%= f.text_field :username, :class => 'logowanie', :placeholder => 'Nazwa Konta' %>
    <%= f.password_field :password, :class => 'logowanie', :placeholder => 'Hasło' %>
    <%= f.check_box :remember_me, :title => 'Zapamiętaj Mnie', :id => 'zapamietaj_mnie' %>
    <%= f.button :Zaloguj, :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<% title "Logowanie" %>
<h1 style="border-bottom: 2px solid rgb(229, 229, 229);"><%= yield(:title) %></h1>

<%= render 'form' %>
<br>
<%= link_to 'Zapomniałem hasła »', '/nie_pamietam_hasla' %> | <%= link_to 'Nie mam konta »', new_user_path %>

app/views/user_sessions/nie_pamietam_hasla.html.erb
<% title "Przypomnienie Hasła" %>
<h1 style="border-bottom: 2px solid rgb(229, 229, 229);"><%= yield(:title) %></h1>
<br><br>
<%= form_tag "/przypomnienie_hasla" do %>
  <b><%= label_tag(:q, "Nick Profilu: ", :class => "label_przypomnienie") %></b>
  <%= text_field_tag(:login_input, nil, :placeholder => "Wpisz swój login") %> <%= submit_tag " Wyślij ", :class => 'button', :id => "wyslij_przypomnienie" %><br><br>

<div style="visibility: visible; left: 150px; top: 135px; opacity: 1;" class="jfk-bubble">
<div class="jfk-bubble-content-id">
<ul id="signupidvusage-bubble-content" class="secondary" style="margin: 0px 18px 0px 18px;">

  <b>Przypomnienie Hasła</b>, <br>
  Po wpisaniu <u>poprawnego</u> loginu z naszego sklepu<br>
  na mail podany przy rejestracji zostanie wysłana<br>
  wiadomość z dalszymi instrukcjami.

  </ul>
</div>
</div>
<% end %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>